/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	uint32_t *pClckCtrlReg=(uint32_t*) 0x40023830;  // Registerin 3. bitini (GPIODEN) enable icin 1 disable icin 0 olacak (Register : AHB1ENR)
	uint32_t *pPortDModeReg=(uint32_t*) 0x40020C00; // 2 bit ile kontrol (01 genel amaçlı out) 24 ve 25. bitler bizi ilgilendiriyor led icin (2y ve 2y+1)
	uint32_t *pPortDOutReg=(uint32_t*) 0x40020C14;  // registerın 12. bitini 1 yapacagız zaten D portu kullanıyoruz reset durumu tamamen 0.

	//once GPIOD icin clock aktif edelim. (AHB1ENR) set işlemi yapacagim yani OR kullanilacak. 3. biti 1 yapacagım maske deger : ...001000 olsun (0.,1.,2. bitler 0 ve 4.,5.,
	//6.,7.,... bitlerde 0 olacak yani maske deger : 0x08 olacak .

	//Registerlar,n baslangicdaki degerlerini okumaliyiz.Onlari maskeleyecegiz sonucta.

    *pClckCtrlReg=*pClckCtrlReg | 0x08;  // *pClckCtrlReg|=0x08; şeklinde de yazılabilir (short hand notation)

    //Şimdi sıradaki adım Pinin modunu output olarak ayarlamak olacaktır. Burda her pin 2 bit kullanılıyordu unutma !
    //01 koymak lazım 24 ve 25 e. Önce bu 2 bitin 0 0 olduğundan emin olalım (clear işlemi "&" kullanılacak) sonra 24 e 1 atarız (set işlemi "|" kullanılacak).
    //Daha shift operatorunu öğrenmediğimden burada kullanmamışım. Maske değeri için her biti 1 yapıp sadece 24 ve 25 i 0 yapmışız.Yani 0xFCFFFFFF maskemiz
    //olacak (bitwise and icin).
    //Sırada 24 dışında hepsini 0 yapacak şey bizim maskemiz olacak. 0x01000000  o 1 4 bitten olusuyor 0001 ve 24. bite karşılık geliyor (saymaya 0 dan başladık).

    *pPortDModeReg &=0xFCFFFFFF;
    *pPortDModeReg |=0x01000000;

    //Simdi ise output data registerinin 12. bitini 1 yapıp işimize bakalım.

    *pPortDOutReg|= 0x1000;


	while(1);
}
